/**
 * @file pdfService.js
 * @description PDFKit-based rendering engine for all Spiro Rwanda PDF reports.
 * Provides shared layout primitives (header, footer, KPI summary, tables)
 * and per-report render functions.
 */

import PDFDocument from 'pdfkit';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ── Brand Constants ──────────────────────────────────────────────────────────
const BRAND = {
  primary: '#3D4C9F',
  primaryLight: '#5A6ABF',
  accent: '#FFE500',
  success: '#10B981',
  warning: '#F59E0B',
  error: '#EF4444',
  textDark: '#1F2937',
  textMuted: '#6B7280',
  tableBorder: '#D1D5DB',
  tableHeaderBg: '#3D4C9F',
  tableRowAlt: '#F3F4F6',
  white: '#FFFFFF',
};

// Resolve logo path — logo lives in frontend/public
const LOGO_PATH = path.resolve(__dirname, '../../../frontend/public/spiro-logo.png');

// ── Bilingual PDF Strings ────────────────────────────────────────────────────
const PDF_STRINGS = {
  en: {
    companyName: 'SPIRO RWANDA',
    companyTagline: 'Electric Mobility Platform',
    report: 'Report',
    period: 'Period',
    generated: 'Generated',
    generatedBy: 'Generated by',
    page: 'Page',
    of: 'of',
    allTime: 'All Time',
    noData: 'No data available for the selected period.',
    copyright: '© 2026 Spiro Rwanda. All rights reserved.',
    confidential: 'CONFIDENTIAL — For authorized personnel only.',
    summary: 'Executive Summary',
    details: 'Detailed Data',
    // Report titles
    swap_operations: 'Swap Operations Summary',
    financial: 'Financial & Revenue Report',
    battery_health: 'Battery Fleet Health Report',
    station_performance: 'Station Performance Report',
    user_activity: 'User Activity Report',
    audit_trail: 'Audit Trail Report',
    daily_station: 'Daily Station Report',
    inventory_status: 'Inventory Status Report',
    maintenance_log: 'Maintenance Log Report',
    swap_history: 'Swap History Receipt',
    payment_statement: 'Payment Statement',
    work_history: 'Work History Report',
  },
  rw: {
    companyName: 'SPIRO RWANDA',
    companyTagline: 'Ikoranabuhanga ry\'Ingendo z\'Amashanyarazi',
    report: 'Raporo',
    period: 'Igihe',
    generated: 'Byakozwe',
    generatedBy: 'Byakozwe na',
    page: 'Urupapuro',
    of: 'kuri',
    allTime: 'Igihe Cyose',
    noData: 'Nta makuru ahari ku gihe wahisemo.',
    copyright: '© 2026 Spiro Rwanda. Uburenganzira bwose bwarinzwe.',
    confidential: 'IBANGA — Ku bantu babifitiye uburenganzira gusa.',
    summary: 'Incamake y\'Ingenzi',
    details: 'Amakuru y\'Ibisobanuro',
    swap_operations: 'Incamake y\'Ibikorwa byo Guhindura',
    financial: 'Raporo y\'Amafaranga n\'Inyungu',
    battery_health: 'Raporo y\'Ubuzima bw\'Imbunda',
    station_performance: 'Raporo y\'Imikorere y\'Ibituro',
    user_activity: 'Raporo y\'Ibikorwa by\'Abakoresha',
    audit_trail: 'Raporo y\'Igenzura',
    daily_station: 'Raporo y\'Umunsi y\'Ikituro',
    inventory_status: 'Raporo y\'Imbunda Zihari',
    maintenance_log: 'Raporo y\'Ubukemurampaka',
    swap_history: 'Ibyakozwe mu Guhindura',
    payment_statement: 'Urutonde rw\'Ubwishyu',
    work_history: 'Raporo y\'Ibikorwa Byakozwe',
  },
};

/**
 * Resolves the language strings to use for the PDF.
 * @param {'en'|'rw'} lang
 * @returns {Object}
 */
function getStrings(lang) {
  return PDF_STRINGS[lang] || PDF_STRINGS.en;
}

/**
 * Formats a date to a human-readable string for PDF display.
 * @param {Date|string} d
 * @returns {string}
 */
function fmtDate(d) {
  if (!d) return 'N/A';
  const date = d instanceof Date ? d : new Date(d);
  return date.toLocaleDateString('en-GB', {
    day: '2-digit', month: 'short', year: 'numeric',
  });
}

/**
 * Formats a datetime with time.
 * @param {Date|string} d
 * @returns {string}
 */
function fmtDateTime(d) {
  if (!d) return 'N/A';
  const date = d instanceof Date ? d : new Date(d);
  return date.toLocaleDateString('en-GB', {
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit', timeZone: 'Africa/Kigali',
  });
}

/**
 * Formats a number as RWF currency.
 * @param {number} n
 * @returns {string}
 */
function fmtRwf(n) {
  if (n == null || isNaN(n)) return 'RWF 0';
  return `RWF ${Number(n).toLocaleString('en-US')}`;
}

/**
 * Shortens large numbers for summary cards.
 * @param {number} n
 * @returns {string}
 */
function fmtCompact(n) {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return String(n);
}

// ── Core PDF Document Factory ────────────────────────────────────────────────

/**
 * Creates a new PDFKit document with standard A4 settings and margins.
 * @returns {PDFDocument}
 */
export function createBaseDocument() {
  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 60, bottom: 60, left: 50, right: 50 },
    info: {
      Title: 'Spiro Rwanda Report',
      Author: 'Spiro Rwanda Platform',
      Creator: 'Spiro Rwanda Platform',
    },
    bufferPages: true, // Enable page buffering for page count in footer
  });

  return doc;
}

// ── Shared Layout Primitives ─────────────────────────────────────────────────

/**
 * Renders the standard report header with logo, company name, and report metadata.
 * @param {PDFDocument} doc
 * @param {{ reportType: string, startDate?: string, endDate?: string, generatedBy?: string, lang?: string }} opts
 */
export function renderHeader(doc, opts = {}) {
  const s = getStrings(opts.lang || 'en');
  const reportTitle = s[opts.reportType] || opts.reportType || s.report;
  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

  // Brand bar at the top
  doc.save();
  doc.rect(0, 0, doc.page.width, 8).fill(BRAND.primary);
  doc.rect(0, 8, doc.page.width, 3).fill(BRAND.accent);
  doc.restore();

  let yPos = 25;

  // Logo
  if (fs.existsSync(LOGO_PATH)) {
    doc.image(LOGO_PATH, doc.page.margins.left, yPos, { width: 45 });
  }

  // Company name and tagline
  doc.fontSize(18).fillColor(BRAND.primary)
    .text(s.companyName, doc.page.margins.left + 55, yPos + 4, { width: pageWidth - 55 });
  doc.fontSize(9).fillColor(BRAND.textMuted)
    .text(s.companyTagline, doc.page.margins.left + 55, yPos + 24, { width: pageWidth - 55 });

  yPos += 50;

  // Horizontal divider
  doc.moveTo(doc.page.margins.left, yPos).lineTo(doc.page.width - doc.page.margins.right, yPos)
    .strokeColor(BRAND.tableBorder).lineWidth(0.5).stroke();

  yPos += 12;

  // Report title
  doc.fontSize(14).fillColor(BRAND.textDark)
    .text(reportTitle, doc.page.margins.left, yPos, { width: pageWidth });
  yPos += 22;

  // Metadata line: period + generation time
  const periodStr = (opts.startDate && opts.endDate)
    ? `${fmtDate(opts.startDate)} — ${fmtDate(opts.endDate)}`
    : s.allTime;
  doc.fontSize(9).fillColor(BRAND.textMuted)
    .text(`${s.period}: ${periodStr}`, doc.page.margins.left, yPos, { width: pageWidth / 2, continued: false });

  doc.fontSize(9).fillColor(BRAND.textMuted)
    .text(`${s.generated}: ${fmtDateTime(new Date())}`, doc.page.margins.left + pageWidth / 2, yPos, {
      width: pageWidth / 2, align: 'right',
    });

  yPos += 14;

  if (opts.generatedBy) {
    doc.fontSize(9).fillColor(BRAND.textMuted)
      .text(`${s.generatedBy}: ${opts.generatedBy}`, doc.page.margins.left, yPos, { width: pageWidth });
    yPos += 14;
  }

  // Bottom divider
  doc.moveTo(doc.page.margins.left, yPos).lineTo(doc.page.width - doc.page.margins.right, yPos)
    .strokeColor(BRAND.tableBorder).lineWidth(0.5).stroke();

  doc.y = yPos + 16;
}

/**
 * Renders the page footer with company name, page number, and confidentiality notice.
 * Must be called AFTER all content is added and before doc.end().
 * Uses bufferPages to add page numbers.
 * @param {PDFDocument} doc
 * @param {{ lang?: string }} opts
 */
export function renderFooters(doc, opts = {}) {
  const s = getStrings(opts.lang || 'en');
  const pageCount = doc.bufferedPageRange().count;

  for (let i = 0; i < pageCount; i++) {
    doc.switchToPage(i);

    const footerY = doc.page.height - 45;
    const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

    // Top divider line
    doc.save();
    doc.moveTo(doc.page.margins.left, footerY)
      .lineTo(doc.page.width - doc.page.margins.right, footerY)
      .strokeColor(BRAND.tableBorder).lineWidth(0.5).stroke();

    // Copyright
    doc.fontSize(7).fillColor(BRAND.textMuted)
      .text(s.copyright, doc.page.margins.left, footerY + 6, { width: pageWidth / 2 });

    // Page number
    doc.fontSize(7).fillColor(BRAND.textMuted)
      .text(`${s.page} ${i + 1} ${s.of} ${pageCount}`, doc.page.margins.left, footerY + 6, {
        width: pageWidth, align: 'center',
      });

    // Confidential notice
    doc.fontSize(7).fillColor(BRAND.textMuted)
      .text(s.confidential, doc.page.margins.left, footerY + 6, {
        width: pageWidth, align: 'right',
      });

    doc.restore();
  }
}

/**
 * Renders a section title with a left accent bar.
 * @param {PDFDocument} doc
 * @param {string} title
 * @param {{ color?: string }} opts
 */
export function renderSectionTitle(doc, title, opts = {}) {
  const color = opts.color || BRAND.primary;
  const y = doc.y;

  // Accent bar
  doc.rect(doc.page.margins.left, y, 3, 16).fill(color);
  doc.fontSize(11).fillColor(BRAND.textDark)
    .text(title, doc.page.margins.left + 10, y + 2);
  doc.y = y + 24;
}

/**
 * Renders a KPI summary grid (up to 4 metrics per row).
 * @param {PDFDocument} doc
 * @param {Array<{ label: string, value: string|number, sub?: string }>} metrics
 */
export function renderKpiSummary(doc, metrics) {
  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  const colCount = Math.min(metrics.length, 4);
  const colWidth = pageWidth / colCount;
  const startY = doc.y;
  const boxHeight = 52;

  for (let i = 0; i < metrics.length; i++) {
    const col = i % colCount;
    const row = Math.floor(i / colCount);
    const x = doc.page.margins.left + col * colWidth;
    const y = startY + row * (boxHeight + 8);

    // Background box
    doc.save();
    doc.roundedRect(x + 2, y, colWidth - 4, boxHeight, 4).fill('#F9FAFB');

    // Value
    doc.fontSize(18).fillColor(BRAND.primary)
      .text(String(metrics[i].value), x + 10, y + 8, { width: colWidth - 20 });

    // Label
    doc.fontSize(8).fillColor(BRAND.textMuted)
      .text(metrics[i].label, x + 10, y + 30, { width: colWidth - 20 });

    // Subtitle
    if (metrics[i].sub) {
      doc.fontSize(7).fillColor(BRAND.textMuted)
        .text(metrics[i].sub, x + 10, y + 40, { width: colWidth - 20 });
    }

    doc.restore();
  }

  const totalRows = Math.ceil(metrics.length / colCount);
  doc.y = startY + totalRows * (boxHeight + 8) + 8;
}

/**
 * Renders a data table with headers and rows.
 * Handles pagination automatically when content overflows the page.
 * @param {PDFDocument} doc
 * @param {{ headers: Array<{ label: string, width: number, align?: string }>, rows: Array<Array<string>> }} tableData
 */
export function renderTable(doc, tableData) {
  const { headers, rows } = tableData;
  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

  // Calculate column widths as proportions
  const totalWidthUnits = headers.reduce((sum, h) => sum + h.width, 0);
  const colWidths = headers.map(h => (h.width / totalWidthUnits) * pageWidth);

  const rowHeight = 20;
  const headerHeight = 24;
  const maxY = doc.page.height - doc.page.margins.bottom - 50; // Leave room for footer

  function drawHeaderRow() {
    const y = doc.y;
    let x = doc.page.margins.left;

    // Header background
    doc.save();
    doc.rect(x, y, pageWidth, headerHeight).fill(BRAND.tableHeaderBg);

    for (let i = 0; i < headers.length; i++) {
      doc.fontSize(8).fillColor(BRAND.white)
        .text(headers[i].label, x + 4, y + 6, {
          width: colWidths[i] - 8,
          align: headers[i].align || 'left',
          lineBreak: false,
        });
      x += colWidths[i];
    }

    doc.restore();
    doc.y = y + headerHeight;
  }

  function drawDataRow(rowData, rowIndex) {
    const y = doc.y;

    // Check if we need a new page
    if (y + rowHeight > maxY) {
      doc.addPage();
      doc.y = doc.page.margins.top + 10;
      drawHeaderRow();
    }

    const currentY = doc.y;
    let x = doc.page.margins.left;

    // Zebra striping
    if (rowIndex % 2 === 1) {
      doc.save();
      doc.rect(x, currentY, pageWidth, rowHeight).fill(BRAND.tableRowAlt);
      doc.restore();
    }

    // Row border
    doc.save();
    doc.moveTo(x, currentY + rowHeight)
      .lineTo(x + pageWidth, currentY + rowHeight)
      .strokeColor(BRAND.tableBorder).lineWidth(0.3).stroke();
    doc.restore();

    for (let i = 0; i < headers.length; i++) {
      const cellValue = (rowData[i] != null) ? String(rowData[i]) : '';
      doc.fontSize(8).fillColor(BRAND.textDark)
        .text(cellValue, x + 4, currentY + 5, {
          width: colWidths[i] - 8,
          align: headers[i].align || 'left',
          lineBreak: false,
        });
      x += colWidths[i];
    }

    doc.y = currentY + rowHeight;
  }

  // Draw the table
  drawHeaderRow();
  rows.forEach((row, idx) => drawDataRow(row, idx));

  doc.y += 12;
}

/**
 * Renders a "no data" message when the report has no records.
 * @param {PDFDocument} doc
 * @param {{ lang?: string }} opts
 */
export function renderNoData(doc, opts = {}) {
  const s = getStrings(opts.lang || 'en');
  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

  doc.y += 30;
  doc.save();
  doc.roundedRect(doc.page.margins.left, doc.y, pageWidth, 40, 4)
    .fillAndStroke('#FEF3C7', '#F59E0B');
  doc.fontSize(10).fillColor(BRAND.textDark)
    .text(s.noData, doc.page.margins.left + 12, doc.y + 13, { width: pageWidth - 24, align: 'center' });
  doc.restore();
  doc.y += 52;
}

// ── Per-Report Render Functions ──────────────────────────────────────────────

/**
 * Renders the Swap Operations Summary report.
 * @param {PDFDocument} doc
 * @param {Object} data - { kpis, swaps }
 * @param {Object} opts - { lang, startDate, endDate, generatedBy }
 */
export function renderSwapOperationsPdf(doc, data, opts = {}) {
  const s = getStrings(opts.lang || 'en');

  renderHeader(doc, { reportType: 'swap_operations', ...opts });

  // KPI Summary
  renderSectionTitle(doc, s.summary);
  renderKpiSummary(doc, [
    { label: 'Total Swaps', value: fmtCompact(data.kpis?.totalSwaps || 0) },
    { label: 'Completed', value: fmtCompact(data.kpis?.completedSwaps || 0) },
    { label: 'Avg Wait Time', value: `${data.kpis?.avgWaitTimeMinutes || 0} min` },
    { label: 'Total Revenue', value: fmtRwf(data.kpis?.totalRevenueRwf || 0) },
  ]);

  // Detailed swap table
  if (data.swaps && data.swaps.length > 0) {
    renderSectionTitle(doc, s.details);
    renderTable(doc, {
      headers: [
        { label: '#', width: 1, align: 'center' },
        { label: 'Date', width: 3 },
        { label: 'Station', width: 3 },
        { label: 'Rider', width: 3 },
        { label: 'Duration', width: 2, align: 'center' },
        { label: 'Amount (RWF)', width: 3, align: 'right' },
        { label: 'Status', width: 2, align: 'center' },
      ],
      rows: data.swaps.map((sw, i) => [
        String(i + 1),
        fmtDate(sw.createdAt || sw.startTime),
        sw.stationId?.name || sw.stationName || 'N/A',
        sw.riderId?.fullName || sw.riderName || 'N/A',
        sw.durationMinutes ? `${sw.durationMinutes} min` : 'N/A',
        sw.amountRwf != null ? Number(sw.amountRwf).toLocaleString() : 'N/A',
        sw.status || 'N/A',
      ]),
    });
  } else {
    renderNoData(doc, opts);
  }
}

/**
 * Renders the Financial/Revenue Report.
 * @param {PDFDocument} doc
 * @param {Object} data - { stats, payments }
 * @param {Object} opts
 */
export function renderFinancialPdf(doc, data, opts = {}) {
  const s = getStrings(opts.lang || 'en');

  renderHeader(doc, { reportType: 'financial', ...opts });

  // KPI Summary
  renderSectionTitle(doc, s.summary);
  renderKpiSummary(doc, [
    { label: 'Total Revenue', value: fmtRwf(data.stats?.totalRevenue || 0) },
    { label: 'Today Revenue', value: fmtRwf(data.stats?.todayRevenue || 0) },
    { label: 'Total Transactions', value: fmtCompact(data.stats?.total || 0) },
    { label: 'Today Transactions', value: String(data.stats?.todayTransactions || 0) },
  ]);

  // Provider breakdown
  if (data.stats?.byProvider) {
    doc.y += 4;
    doc.fontSize(9).fillColor(BRAND.textDark)
      .text('Revenue by Provider:', doc.page.margins.left, doc.y);
    doc.y += 14;
    const providers = Object.entries(data.stats.byProvider);
    for (const [provider, count] of providers) {
      doc.fontSize(8).fillColor(BRAND.textMuted)
        .text(`  • ${provider.replace('_', ' ').toUpperCase()}: ${count} transactions`, doc.page.margins.left, doc.y);
      doc.y += 12;
    }
    doc.y += 6;
  }

  // Payments table
  if (data.payments && data.payments.length > 0) {
    renderSectionTitle(doc, s.details);
    renderTable(doc, {
      headers: [
        { label: '#', width: 1, align: 'center' },
        { label: 'Transaction ID', width: 3 },
        { label: 'Date', width: 3 },
        { label: 'Rider', width: 3 },
        { label: 'Provider', width: 2 },
        { label: 'Type', width: 2 },
        { label: 'Amount (RWF)', width: 3, align: 'right' },
        { label: 'Status', width: 2, align: 'center' },
      ],
      rows: data.payments.map((p, i) => [
        String(i + 1),
        p.transactionId || 'N/A',
        fmtDate(p.createdAt),
        p.riderId?.fullName || 'N/A',
        (p.provider || '').replace('_', ' '),
        (p.type || '').replace('_', ' '),
        Number(p.amountRwf || 0).toLocaleString(),
        p.refunded ? 'Refunded' : (p.status || 'N/A'),
      ]),
    });
  } else {
    renderNoData(doc, opts);
  }
}

/**
 * Renders the Battery Fleet Health Report.
 * @param {PDFDocument} doc
 * @param {Object} data - { summary, batteries }
 * @param {Object} opts
 */
export function renderBatteryHealthPdf(doc, data, opts = {}) {
  const s = getStrings(opts.lang || 'en');

  renderHeader(doc, { reportType: 'battery_health', ...opts });

  renderSectionTitle(doc, s.summary);
  renderKpiSummary(doc, [
    { label: 'Total Batteries', value: String(data.summary?.total || 0) },
    { label: 'Available', value: String(data.summary?.available || 0) },
    { label: 'Charging', value: String(data.summary?.charging || 0) },
    { label: 'Faulty', value: String(data.summary?.faulty || 0) },
  ]);

  if (data.batteries && data.batteries.length > 0) {
    renderSectionTitle(doc, s.details);
    renderTable(doc, {
      headers: [
        { label: '#', width: 1, align: 'center' },
        { label: 'Serial Number', width: 3 },
        { label: 'Station', width: 3 },
        { label: 'Status', width: 2, align: 'center' },
        { label: 'Charge %', width: 2, align: 'center' },
        { label: 'Health', width: 2, align: 'center' },
        { label: 'Cycles', width: 2, align: 'center' },
        { label: 'Repairs', width: 1, align: 'center' },
      ],
      rows: data.batteries.map((b, i) => [
        String(i + 1),
        b.serialNumber || 'N/A',
        b.stationId?.name || b.stationName || 'Unassigned',
        b.status || 'N/A',
        b.chargeLevel != null ? `${b.chargeLevel}%` : 'N/A',
        b.healthStatus || 'N/A',
        String(b.cycleCount || 0),
        String(b.repairCount || 0),
      ]),
    });
  } else {
    renderNoData(doc, opts);
  }
}

/**
 * Renders the Station Performance Report.
 * @param {PDFDocument} doc
 * @param {Object} data - { stations }
 * @param {Object} opts
 */
export function renderStationPerformancePdf(doc, data, opts = {}) {
  const s = getStrings(opts.lang || 'en');

  renderHeader(doc, { reportType: 'station_performance', ...opts });

  if (data.stations && data.stations.length > 0) {
    renderSectionTitle(doc, s.details);
    renderTable(doc, {
      headers: [
        { label: '#', width: 1, align: 'center' },
        { label: 'Station', width: 4 },
        { label: 'Province', width: 2 },
        { label: 'Status', width: 2, align: 'center' },
        { label: 'Total Swaps', width: 2, align: 'center' },
        { label: 'Avg Wait (min)', width: 2, align: 'center' },
        { label: 'Revenue (RWF)', width: 3, align: 'right' },
        { label: 'Maintenance', width: 2, align: 'center' },
      ],
      rows: data.stations.map((st, i) => [
        String(i + 1),
        st.name || 'N/A',
        st.province || 'N/A',
        st.status || 'N/A',
        String(st.totalSwaps || 0),
        String(st.avgWaitTimeMinutes || 0),
        Number(st.revenueRwf || 0).toLocaleString(),
        String(st.maintenanceIncidents || 0),
      ]),
    });
  } else {
    renderNoData(doc, opts);
  }
}

/**
 * Renders the User Activity Report.
 * @param {PDFDocument} doc
 * @param {Object} data - { summary, users }
 * @param {Object} opts
 */
export function renderUserActivityPdf(doc, data, opts = {}) {
  const s = getStrings(opts.lang || 'en');

  renderHeader(doc, { reportType: 'user_activity', ...opts });

  renderSectionTitle(doc, s.summary);
  renderKpiSummary(doc, [
    { label: 'Total Users', value: String(data.summary?.total || 0) },
    { label: 'Riders', value: String(data.summary?.riders || 0) },
    { label: 'Operators', value: String(data.summary?.operators || 0) },
    { label: 'Technicians', value: String(data.summary?.technicians || 0) },
  ]);

  if (data.users && data.users.length > 0) {
    renderSectionTitle(doc, s.details);
    renderTable(doc, {
      headers: [
        { label: '#', width: 1, align: 'center' },
        { label: 'Name', width: 4 },
        { label: 'Phone', width: 3 },
        { label: 'Role', width: 2, align: 'center' },
        { label: 'Status', width: 2, align: 'center' },
        { label: 'Registered', width: 3 },
        { label: 'Last Login', width: 3 },
      ],
      rows: data.users.map((u, i) => [
        String(i + 1),
        u.fullName || 'N/A',
        u.phone || 'N/A',
        u.role || 'N/A',
        u.isActive ? 'Active' : 'Inactive',
        fmtDate(u.createdAt),
        u.lastLoginAt ? fmtDate(u.lastLoginAt) : 'Never',
      ]),
    });
  } else {
    renderNoData(doc, opts);
  }
}

/**
 * Renders the Audit Trail Report.
 * @param {PDFDocument} doc
 * @param {Object} data - { entries }
 * @param {Object} opts
 */
export function renderAuditTrailPdf(doc, data, opts = {}) {
  const s = getStrings(opts.lang || 'en');

  renderHeader(doc, { reportType: 'audit_trail', ...opts });

  if (data.entries && data.entries.length > 0) {
    renderSectionTitle(doc, s.details);
    renderTable(doc, {
      headers: [
        { label: '#', width: 1, align: 'center' },
        { label: 'Timestamp', width: 3 },
        { label: 'Event', width: 3 },
        { label: 'Actor', width: 3 },
        { label: 'Role', width: 2, align: 'center' },
        { label: 'Description', width: 6 },
      ],
      rows: data.entries.map((e, i) => [
        String(i + 1),
        fmtDateTime(e.timestamp),
        e.eventType || 'N/A',
        e.actorUserId?.fullName || e.actorName || 'System',
        e.actorRole || 'N/A',
        (e.description || 'N/A').substring(0, 60),
      ]),
    });
  } else {
    renderNoData(doc, opts);
  }
}

/**
 * Renders the Daily Station Report.
 * @param {PDFDocument} doc
 * @param {Object} data - { station, kpis, swaps, batteries }
 * @param {Object} opts
 */
export function renderDailyStationPdf(doc, data, opts = {}) {
  const s = getStrings(opts.lang || 'en');

  renderHeader(doc, { reportType: 'daily_station', ...opts });

  if (data.station) {
    doc.fontSize(10).fillColor(BRAND.textDark)
      .text(`Station: ${data.station.name || 'N/A'}`, doc.page.margins.left, doc.y);
    if (data.station.address) {
      doc.fontSize(8).fillColor(BRAND.textMuted)
        .text(`Address: ${data.station.address}`, doc.page.margins.left, doc.y + 2);
    }
    doc.y += 20;
  }

  renderSectionTitle(doc, s.summary);
  renderKpiSummary(doc, [
    { label: 'Swaps Today', value: String(data.kpis?.todaySwaps || 0) },
    { label: 'Revenue Today', value: fmtRwf(data.kpis?.todayRevenue || 0) },
    { label: 'Available Batteries', value: String(data.kpis?.availableBatteries || 0) },
    { label: 'Charging Batteries', value: String(data.kpis?.chargingBatteries || 0) },
  ]);

  if (data.swaps && data.swaps.length > 0) {
    renderSectionTitle(doc, s.details);
    renderTable(doc, {
      headers: [
        { label: '#', width: 1, align: 'center' },
        { label: 'Time', width: 3 },
        { label: 'Rider', width: 3 },
        { label: 'Battery Out', width: 2 },
        { label: 'Battery In', width: 2 },
        { label: 'Duration', width: 2, align: 'center' },
        { label: 'Amount (RWF)', width: 2, align: 'right' },
        { label: 'Status', width: 2, align: 'center' },
      ],
      rows: data.swaps.map((sw, i) => [
        String(i + 1),
        fmtDateTime(sw.startTime || sw.createdAt),
        sw.riderId?.fullName || 'N/A',
        sw.depletedBatteryId?.serialNumber || 'N/A',
        sw.chargedBatteryId?.serialNumber || 'N/A',
        sw.durationMinutes ? `${sw.durationMinutes} min` : 'N/A',
        Number(sw.amountRwf || 0).toLocaleString(),
        sw.status || 'N/A',
      ]),
    });
  } else {
    renderNoData(doc, opts);
  }
}

/**
 * Renders the Inventory Status Report.
 * @param {PDFDocument} doc
 * @param {Object} data - { station, batteries, summary }
 * @param {Object} opts
 */
export function renderInventoryStatusPdf(doc, data, opts = {}) {
  const s = getStrings(opts.lang || 'en');

  renderHeader(doc, { reportType: 'inventory_status', ...opts });

  if (data.station) {
    doc.fontSize(10).fillColor(BRAND.textDark)
      .text(`Station: ${data.station.name || 'N/A'}`, doc.page.margins.left, doc.y);
    doc.y += 16;
  }

  renderSectionTitle(doc, s.summary);
  renderKpiSummary(doc, [
    { label: 'Total Batteries', value: String(data.summary?.total || 0) },
    { label: 'Available', value: String(data.summary?.available || 0) },
    { label: 'Charging', value: String(data.summary?.charging || 0) },
    { label: 'Faulty', value: String(data.summary?.faulty || 0) },
  ]);

  if (data.batteries && data.batteries.length > 0) {
    renderSectionTitle(doc, s.details);
    renderTable(doc, {
      headers: [
        { label: '#', width: 1, align: 'center' },
        { label: 'Serial Number', width: 4 },
        { label: 'Status', width: 2, align: 'center' },
        { label: 'Charge %', width: 2, align: 'center' },
        { label: 'Health', width: 2, align: 'center' },
        { label: 'Last Swap', width: 3 },
        { label: 'Cycles', width: 2, align: 'center' },
      ],
      rows: data.batteries.map((b, i) => [
        String(i + 1),
        b.serialNumber || 'N/A',
        b.status || 'N/A',
        b.chargeLevel != null ? `${b.chargeLevel}%` : 'N/A',
        b.healthStatus || 'N/A',
        b.lastSwapAt ? fmtDate(b.lastSwapAt) : 'Never',
        String(b.cycleCount || 0),
      ]),
    });
  } else {
    renderNoData(doc, opts);
  }
}

/**
 * Renders the Maintenance Log Report.
 * @param {PDFDocument} doc
 * @param {Object} data - { requests }
 * @param {Object} opts
 */
export function renderMaintenanceLogPdf(doc, data, opts = {}) {
  const s = getStrings(opts.lang || 'en');

  renderHeader(doc, { reportType: 'maintenance_log', ...opts });

  if (data.requests && data.requests.length > 0) {
    renderSectionTitle(doc, s.details);
    renderTable(doc, {
      headers: [
        { label: '#', width: 1, align: 'center' },
        { label: 'Date', width: 3 },
        { label: 'Station', width: 3 },
        { label: 'Equipment', width: 3 },
        { label: 'Urgency', width: 2, align: 'center' },
        { label: 'Status', width: 2, align: 'center' },
        { label: 'Technician', width: 3 },
        { label: 'Resolved', width: 3 },
      ],
      rows: data.requests.map((r, i) => [
        String(i + 1),
        fmtDate(r.createdAt),
        r.stationId?.name || r.stationName || 'N/A',
        r.equipment || 'N/A',
        r.urgency || 'N/A',
        r.status || 'N/A',
        r.assignedTechnician?.fullName || 'Unassigned',
        r.resolvedAt ? fmtDate(r.resolvedAt) : '—',
      ]),
    });
  } else {
    renderNoData(doc, opts);
  }
}

/**
 * Renders the Swap History Receipt (Rider).
 * @param {PDFDocument} doc
 * @param {Object} data - { rider, swaps, totalSpent }
 * @param {Object} opts
 */
export function renderSwapHistoryPdf(doc, data, opts = {}) {
  const s = getStrings(opts.lang || 'en');

  renderHeader(doc, { reportType: 'swap_history', ...opts });

  if (data.rider) {
    doc.fontSize(10).fillColor(BRAND.textDark)
      .text(`Rider: ${data.rider.fullName || 'N/A'}`, doc.page.margins.left, doc.y);
    doc.fontSize(8).fillColor(BRAND.textMuted)
      .text(`Phone: ${data.rider.phone || 'N/A'}`, doc.page.margins.left, doc.y + 2);
    doc.y += 20;
  }

  renderSectionTitle(doc, s.summary);
  renderKpiSummary(doc, [
    { label: 'Total Swaps', value: String(data.swaps?.length || 0) },
    { label: 'Total Spent', value: fmtRwf(data.totalSpent || 0) },
  ]);

  if (data.swaps && data.swaps.length > 0) {
    renderSectionTitle(doc, s.details);
    renderTable(doc, {
      headers: [
        { label: '#', width: 1, align: 'center' },
        { label: 'Date', width: 3 },
        { label: 'Station', width: 4 },
        { label: 'Duration', width: 2, align: 'center' },
        { label: 'Amount (RWF)', width: 3, align: 'right' },
        { label: 'Status', width: 2, align: 'center' },
      ],
      rows: data.swaps.map((sw, i) => [
        String(i + 1),
        fmtDate(sw.createdAt || sw.startTime),
        sw.stationId?.name || 'N/A',
        sw.durationMinutes ? `${sw.durationMinutes} min` : 'N/A',
        Number(sw.amountRwf || 0).toLocaleString(),
        sw.status || 'N/A',
      ]),
    });
  } else {
    renderNoData(doc, opts);
  }
}

/**
 * Renders the Payment Statement (Rider).
 * @param {PDFDocument} doc
 * @param {Object} data - { rider, payments, totalAmount }
 * @param {Object} opts
 */
export function renderPaymentStatementPdf(doc, data, opts = {}) {
  const s = getStrings(opts.lang || 'en');

  renderHeader(doc, { reportType: 'payment_statement', ...opts });

  if (data.rider) {
    doc.fontSize(10).fillColor(BRAND.textDark)
      .text(`Rider: ${data.rider.fullName || 'N/A'}`, doc.page.margins.left, doc.y);
    doc.fontSize(8).fillColor(BRAND.textMuted)
      .text(`Phone: ${data.rider.phone || 'N/A'}`, doc.page.margins.left, doc.y + 2);
    doc.y += 20;
  }

  renderSectionTitle(doc, s.summary);
  renderKpiSummary(doc, [
    { label: 'Total Payments', value: String(data.payments?.length || 0) },
    { label: 'Total Amount', value: fmtRwf(data.totalAmount || 0) },
  ]);

  if (data.payments && data.payments.length > 0) {
    renderSectionTitle(doc, s.details);
    renderTable(doc, {
      headers: [
        { label: '#', width: 1, align: 'center' },
        { label: 'Date', width: 3 },
        { label: 'Transaction ID', width: 3 },
        { label: 'Type', width: 2 },
        { label: 'Provider', width: 2 },
        { label: 'Amount (RWF)', width: 3, align: 'right' },
        { label: 'Status', width: 2, align: 'center' },
      ],
      rows: data.payments.map((p, i) => [
        String(i + 1),
        fmtDate(p.createdAt),
        p.transactionId || 'N/A',
        (p.type || '').replace(/_/g, ' '),
        (p.provider || '').replace(/_/g, ' '),
        Number(p.amountRwf || 0).toLocaleString(),
        p.status || 'N/A',
      ]),
    });
  } else {
    renderNoData(doc, opts);
  }
}

/**
 * Renders the Technician Work History Report.
 * @param {PDFDocument} doc
 * @param {Object} data - { technician, tasks, totalResolved }
 * @param {Object} opts
 */
export function renderWorkHistoryPdf(doc, data, opts = {}) {
  const s = getStrings(opts.lang || 'en');

  renderHeader(doc, { reportType: 'work_history', ...opts });

  if (data.technician) {
    doc.fontSize(10).fillColor(BRAND.textDark)
      .text(`Technician: ${data.technician.fullName || 'N/A'}`, doc.page.margins.left, doc.y);
    doc.y += 16;
  }

  renderSectionTitle(doc, s.summary);
  renderKpiSummary(doc, [
    { label: 'Total Tasks', value: String(data.tasks?.length || 0) },
    { label: 'Resolved', value: String(data.totalResolved || 0) },
  ]);

  if (data.tasks && data.tasks.length > 0) {
    renderSectionTitle(doc, s.details);
    renderTable(doc, {
      headers: [
        { label: '#', width: 1, align: 'center' },
        { label: 'Date', width: 3 },
        { label: 'Station', width: 3 },
        { label: 'Equipment', width: 3 },
        { label: 'Urgency', width: 2, align: 'center' },
        { label: 'Status', width: 2, align: 'center' },
        { label: 'Resolved At', width: 3 },
      ],
      rows: data.tasks.map((t, i) => [
        String(i + 1),
        fmtDate(t.createdAt),
        t.stationId?.name || 'N/A',
        t.equipment || 'N/A',
        t.urgency || 'N/A',
        t.status || 'N/A',
        t.resolvedAt ? fmtDate(t.resolvedAt) : '—',
      ]),
    });
  } else {
    renderNoData(doc, opts);
  }
}
